SaschaWillems/VulkanCapsViewer

vulkancapsviewer.cpp

Hey!
I was curious why all the memory type flags were saying "true" on my system. It turned out to be a simple typo in bit testing code. Here's a fix!
Thanks for the app, btw. It's super useful :)

Fixed the display of flags associated with memory types and heaps.

---

README.md

I wasn't sure whether to add the links to the sources ([Layers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers) & [Tools](https://github.com/LunarG/VulkanTools)), so I just went with that.

Add link to Vulkan SDK

---

vulkanDeviceInfo.hpp

On Archlinux with gcc gcc 8.1 calling QVariant(uint64_t) causes an error
call of overloaded 'QVariant(VkDeviceSize&)' is ambiguous

Fix QVariant(VkDeviceSize&) is ambiguous

---

vulkanDeviceInfo.hpp

This fixes all errors like the following:
```
vulkanDeviceInfo.hpp:483:120: error: call of overloaded ‘QVariant(VkDeviceSize&)’ is ambiguous
pushProperty2(extension, "maxTransformFeedbackBufferSize", QVariant(extProps.maxTransformFeedbackBufferSize));
```
My GCC:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-8.2.0-r4/work/gcc-8.2.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.2.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.2.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.2.0/man …
```

Fix ambigious calls to QVariant()

---

vulkanCapsViewer.desktop
vulkanCapsViewer.pro

I've been adding these to the package I maintain for ArchLinux, but I think they should be part of the upstream repo (ie. here) instead of being done by each packager.

Add and install a .desktop file

---

vulkancapsviewer.cpp
vulkansurfaceinfo.hpp

Helps un-supported systems or systems without surface exts from failing to startup or hang during getting surface information. This is allows MoltenVk to work, minus any surface info.

Improved behaviour if no surface extensions are detected.

---

vulkanDeviceInfo.cpp
vulkanDeviceInfo.h
vulkancapsviewer.cpp
vulkancapsviewer.ui
vulkanresources.h

- update some Flags and Enums
- show Flags consistently
- shows hex at flag root
- lists supported bits
- lists unknown supported bits with a hex
- show VID:PID in hex
- show UUID in canonical form
- show bool Limits as bool
- fix #1: show samples as a list of supported counts
- do not use Vk version format for revision numbers
- fix Bool color in Queues tab
- consistent array formatting
- show array size as C notation
- show index as C notation
- some random cleanup

Tweak formatting of reported values

---

vulkanCapsViewer.pro
vulkancapsviewer.cpp

#86 had many issues and was entirely unusable for multiple reasons (see the first commit for details)
This new version compiles support for both X11 and Wayland and chooses at runtime which one to use (it tests Wayland, and if it doesn't work it tests X11; doing it the other way around would use X11 on Wayland as virtually every Wayland compositor supports Xwayland).
The compiled binary has been tested and works on both X11 and on Wayland, and is valgrind-clean.
**Note:** ~~I am not very familiar with Qmake and I was unable to figure out how to auto-detect the presence of the Wayland libraries, which means that starting now the Qt5Wayland libs are required to build VulkanCapsViewer on Linux.~~
Edit: Both X11 and Wayland are now build-optional. If you want the runtime option to use them, …

Wayland support (for real this time)

---

vulkancapsviewer.cpp

I ran into this case of possibleSurfaceExtensions being empty. Then
the surface is being queried in VulkanDeviceInfo::readQueueFamilies()
and it crashes in the implementation because the pointer is invalid.
Signed-off-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>

Initialize surface member to NULL

---

vulkanCapsViewer.pro
vulkanDeviceInfo.h
vulkancapsviewer.cpp

- Use qtHaveModule() function to look for wayland and xcb qt modules. No need to pass a define to it anymore that way. Currently if X11 or WAYLAND define isn't passed to qmake surface tab is always empty
- Use QPA to obtain api specific handles. QPA is more reliable way to get them, doesn't require fishy things like passing NULL as wayland surface to vkCreateWaylandSurfaceKHR. QPA itself is a private interface that doesn't maintain binary compatibility, but this at least shouldn't be a problem for AppImage afaict.
This should resolve issue #140

Fix surface page on linux

---

.github/workflows/build.yml

This PR is related to the issue I reported in #164.
Comparison of extracted AppImages 3.27 (last working one) vs. 3.28 (first one where the issue is visible) shows that the later one includes libwayland-client.so library:
```
$ diff -qr vulkancapsviewer_3.27_linux64_wayland/ vulkancapsviewer_3.28_linux64_wayland/
Files vulkancapsviewer_3.27_linux64_wayland/squashfs-root/AppRun and vulkancapsviewer_3.28_linux64_wayland/squashfs-root/AppRun differ
Files vulkancapsviewer_3.27_linux64_wayland/squashfs-root/usr/bin/vulkanCapsViewer and vulkancapsviewer_3.28_linux64_wayland/squashfs-root/usr/bin/vulkanCapsViewer differ
Files vulkancapsviewer_3.27_linux64_wayland/squashfs-root/usr/lib/libdbus-1.so.3 and vulkancapsviewer_3.28_linux64_wayland/squashfs-root/usr/lib/libdbus-1.so.3 differ
Only in …
```

Do not include libwayland-client.so within AppImage for Linux/Wayland

---

flatpak/flatpak_install.patch
flatpak/org.vulkanCapsViewer.VulkanCapsViewer.yml

This adds manifest to make a flatpak of VulkanCapsViewer. It has an advantage over appimage of not being coupled with particular glibc versions, because flatpak runtime provides own glibc. Potentially this manifest could be used to upload the app to Flathub, but this use case probably needs extra work.
Steps to test:
```
cd flatpak
flatpak-builder --user --install --force-clean flatpak-output org.vulkanCapsViewer.VulkanCapsViewer.yml
flatpak run org.vulkanCapsViewer.VulkanCapsViewer
```

Add flatpak manifest

---

README.md

I added useful pieces of information for choosing the windowing system when building on Linux. By default when calling qmake without the required definitions, Linux builds lack support for surface and presentation queues.

Additional information for building on linux.

---

VulkanDeviceInfoExtensions.cpp
android/build.gradle

This patch changes 2 things that may be unrelated (individual commits):
- Fix a compilation error when building the app with Clang on Android (Passing an `unsigned long` to QVariant from Qt 5.15)
- Lower the minimal and target Android SDK to version 29 in the main Gradle file. This allows building the app for devices stuck on Android 10 (Pico 4 and Oculus Quest 1 headset for example)

Permit to build APK compatible with Pico 4 XR headset

---

vulkancapsviewer.ui

Trivial issues found during Vulkan SDK testing.
"Impementation" was misspelled.
"Queue Families" had both words capitalized in one place, but one capitalized and the other lowercase in another place.

ui: fix minor spelling and consistency

---

appleutils.mm
vulkanCapsViewer.pro
vulkancapsviewer.cpp
vulkancapsviewer.h

This PR adds the missing surface information on iOS and macOS machines. This is in Queue Families tab and the Surface tab.

Fix for missing surface info on macOS and iOS

---

CMakeLists.txt

Also lets the script default to the Vulkan-Headers submodule for ease-of-use.

Fix: Use C++17 as standard in CMake script

---

vulkanCapsViewer.pro
vulkanDeviceInfo.h
vulkancapsviewer.cpp

Replaces #222 (I accidentally overwrote the branch, but this does everything that PR does but better).
Fixes #224

surface: Better support for linux surface backends

---

vulkancapsviewer.cpp

Commit based on #232.
Prioritizes surface extensions in the order they are defined in code.
In practice this means Wayland > XCB on Linux as other OSes are 1:1.

Dynamic window system choice

---

vulkanCapsViewer.pro

The current Play Store release of VulkanCapsViewer supports only arm64-v8a devices, leaving out data for lower end 32bit Android devices in the database. This PR enables multi ABI builds by assigning separate object and moc directories for each ABI, which prevents file overwrites that cause link-time errors. Note that multi ABI support still needs to be manually selected in the Qt build settings. It would be great to add 32 bit support so developers can easily see Vulkan features on lower end android devices.

Enable Multi-ABI support for android builds
